### ISSUE TITLE
error in deploy script

### ISSUE THREAD

**Issue by shimondoodkin** [playtomic/apiserver#4]
There was a problem with the app.json file found at "https://github.com/playtomic/apiserver/tree/master":
The plan "sandbox" for the addon "mongohq" does not exist. Please ensure that the plan is spelled correctly.

**Comment by benlowry** [comment]
I'm guessing this is related to their company renaming as Compose, sorting it out now!

**Comment by benlowry** [comment]
Actually no they appear to have removed their entry level plan which was free, I'm going to swap it out for another mongodb provider.
